#
#    The FreeBSD Documentation Project
#    The FreeBSD French Documentation Project
#
#    $FreeBSD: head/fr_FR.ISO8859-1/articles/Makefile 48282 2016-02-27 16:10:01Z blackend $
#    Original revision: 1.3
#

SUBDIR =
SUBDIR+= bsdl-gpl
SUBDIR+= building-products
SUBDIR+= committers-guide
SUBDIR+= contributing
SUBDIR+= contributors
SUBDIR+= explaining-bsd
SUBDIR+= filtering-bridges
SUBDIR+= fonts
SUBDIR+= ipsec-must
SUBDIR+= leap-seconds
SUBDIR+= linux-users
SUBDIR+= nanobsd
SUBDIR+= new-users
SUBDIR+= pam
SUBDIR+= pr-guidelines
SUBDIR+= problem-reports

ROOT_SYMLINKS+= new-users

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
