# $FreeBSD: head/nl_NL.ISO8859-1/articles/Makefile 47355 2015-09-03 20:46:30Z rene $

SUBDIR =
SUBDIR+= contributing
SUBDIR+= cups
SUBDIR+= explaining-bsd
SUBDIR+= leap-seconds
SUBDIR+= problem-reports
SUBDIR+= solid-state

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
