# $FreeBSD: head/it_IT.ISO8859-15/books/Makefile 52099 2018-08-11 01:23:04Z eadler $

SUBDIR = arch-handbook
SUBDIR+= design-44bsd
SUBDIR+= dev-model
SUBDIR+= developers-handbook
SUBDIR+= faq
SUBDIR+= fdp-primer
SUBDIR+= handbook
SUBDIR+= porters-handbook

ROOT_SYMLINKS= handbook

DOC_PREFIX?= ${.CURDIR}/../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
