# $FreeBSD: head/it_IT.ISO8859-15/Makefile 52099 2018-08-11 01:23:04Z eadler $

SUBDIR= articles
SUBDIR+= books

COMPAT_SYMLINK = it

DOC_PREFIX?= ${.CURDIR}/..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
