#
# Build the Porters Handbook with just the content from this chapter.
#
# $FreeBSD: head/en_US.ISO8859-1/books/porters-handbook/order/Makefile 50619 2017-08-02 12:19:40Z mat $
#

CHAPTERS= 	order/chapter.xml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
