#
# The FreeBSD Simplified Chinese Project
#
# Original Revision: 1.14
# $FreeBSD: head/zh_CN.UTF-8/books/Makefile 38826 2012-05-17 19:12:14Z hrs $

SUBDIR = arch-handbook
SUBDIR+= developers-handbook
SUBDIR+= handbook
SUBDIR+= porters-handbook

ROOT_SYMLINKS= handbook

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
