# $FreeBSD: head/en_US.ISO8859-1/books/Makefile 52714 2018-12-23 21:22:52Z crees $

SUBDIR = arch-handbook
SUBDIR+= design-44bsd
SUBDIR+= dev-model
SUBDIR+= developers-handbook
SUBDIR+= faq
SUBDIR+= fdp-primer
SUBDIR+= handbook
SUBDIR+= porters-handbook

ROOT_SYMLINKS= faq handbook

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
